export const inputList = [
  {
    tag: "textarea",
    id: "message",
    name: "message",
    type: "text",
    label: "Message",
    required: true,
    rows: 8,
  },
  {
    tag: "input",
    id: "name",
    name: "name",
    type: "text",
    label: "Your Name",
    placeholder: "",
    required: true,
  },
  {
    tag: "input",
    id: "company-name",
    name: "companyName",
    type: "text",
    label: "Company Name",
    placeholder: "Example Company",
    required: false,
  },
  {
    tag: "input",
    id: "email",
    name: "email",
    type: "email",
    label: "Email",
    required: true,
    placeholder: "example@gmail.com",
  },
  {
    tag: "input",
    id: "phone-number",
    name: "phoneNumber",
    type: "text",
    label: "Phone Number",
    required: true,
    placeholder: "000-0000-0000",
    pattern: "^[0-9]{2,3}(-|\\s)*[0-9]{4}(-|\\s)*[0-9]{4}$",
  },
];